<div style="background:#f5f5f7; border:2px solid #d0d0d5; padding:20px; border-radius:12px;">

# **Naive GNN Approach — Beginner-Friendly Explanation**

### <span style="color:#4a4a4f;">Understanding how neural networks can work on graph data</span>

Graphs are special because they are made of **three different types of information**:

* **Nodes** (things)
* **Edges** (relationships between things)
* **Global information** (a single vector describing the entire graph)

In normal neural networks, data usually has a fixed shape (like an image grid or a sequence). But graphs are irregular — each graph can have a different number of nodes and edges. So we need to think differently.

This part of your instructor’s presentation is showing the **very first**, **simplest possible**, **connectivity-free** graph neural network.

---

## **What is the Naive Approach?**

This approach tries to answer one simple question:

> *If I have vectors for nodes, edges, and the whole graph, can I learn better versions of those vectors using neural networks?*

The answer is **yes**, and we do this using **MLPs** (Multilayer Perceptrons).

But here is the key idea:

<div style="background:#ffffff; border-left: 4px solid #6a6a75; padding:10px;">
Each node, each edge, and the global graph vector is processed **independently**, with **no use of graph connectivity**.
</div>

This is why this method is called **naive**.

---

## **Step-by-Step Explanation (No Leaps)**

### **1. Every node has a feature vector**

For example:

* A molecule atom may have features like its type, electric charge, etc.
* A social network user may have features like age or interests.

Let’s call the feature of a node:

x_v

### **2. Every edge has a feature vector**

Edges connect two nodes, but in the naive model, we ignore that connection.

Let an edge feature be:

x_e

### **3. The whole graph has a single global vector**

This is optional but useful.

Let it be:

u

---

## **4. Apply a separate MLP to each type of feature**

We use three different neural networks:

* **MLP_V** → updates each node
* **MLP_E** → updates each edge
* **MLP_U** → updates the global feature

So we compute:

new_node_feature = MLP_V(old_node_feature)
new_edge_feature = MLP_E(old_edge_feature)
new_global_feature = MLP_U(old_global_feature)

Each node gets updated **independently**, each edge gets updated **independently**, and the global graph feature gets updated **independently**.

No messages. No neighbors. No structure.

---

## **Why this is called a “GNN Layer”?**

Because the input is a graph (in the form of its attributes), and the output is *also* a graph with updated attributes.

Technically, it **does** operate on graph data, even though it ignores connections.

Also, as with normal neural networks, you can **stack several layers** of this.

---

## **Why teach this naive approach first?**

Because it answers the most basic question:

<div style="background:#ffffff; border-left: 4px solid #6a6a75; padding:10px;">
<b>How do we even begin to apply neural networks to graphs?</b>
</div>

Before introducing real GNNs (which use neighbors and message passing), your instructor wants you to understand the simplest functional building block.

---

## **Limitations (Why this is not enough)**

This simple approach **cannot**:

* Learn from graph connectivity
* Detect patterns like triangles or chains
* Use which nodes are neighbors
* Distinguish graphs with the same node features but different shapes

In other words:

> *This approach learns from features, not structure.*

This is why the next stage of the course will introduce **message passing**, which *does* use the graph structure.

---

## **Visual Summary (from the slide)**

* Each attribute type (Nodes, Edges, Global) is fed into its own MLP.
* The output is a new graph whose attributes are updated.
* Structure is ignored.
* This is the simplest possible GNN layer.

---

# **End of Explanation**

If you want, I can also prepare separate markdown cells for:

* A comparison with real message-passing GNNs
* A diagram in ASCII art
* A second markdown cell for the next slide
* A compact summary box for your PDF

Just tell me what you want next.

## **Step-by-step — visual, intuitive example**

<div style="background:#ffffff; border-left:4px solid #3a3a40; padding:12px; border-radius:8px;">

**Graph layout (picture it left-to-right):**

A — B — C

* Nodes: **A**, **B**, **C**
* Edges: **e1** connects A–B, **e2** connects B–C
* Global vector: **G** (one small vector describing whole graph)

**Initial (simple) features — imagine these as short lists of numbers):**

* A: [1, 0]
* B: [0, 1]
* C: [1, 1]
* e1 (A–B): [0.5]
* e2 (B–C): [0.2]
* Global G: [0]

> These are tiny example feature vectors so you can *see* the numbers transform. They are illustrative — not outputs of a real MLP.

---

### **Step 1 — look at a single layer of the naive GNN**

* The model contains three separate small MLPs: **MLP_V** (for nodes), **MLP_E** (for edges), **MLP_U** (for global).
* Importantly: **each node is processed alone** — it does not see its neighbours.

**Apply the node-MLP to each node individually:**

* A_new = MLP_V(A) → imagine it maps [1,0] → [0.9, 0.1]
* B_new = MLP_V(B) → [0,1] → [0.2, 0.8]
* C_new = MLP_V(C) → [1,1] → [0.6, 0.7]

**Apply the edge-MLP to each edge individually:**

* e1_new = MLP_E(e1) → [0.5] → [0.45]
* e2_new = MLP_E(e2) → [0.2] → [0.18]

**Apply the global-MLP to the global vector:**

* G_new = MLP_U(G) → [0] → [0.05]

> Notice: None of the node outputs used A’s neighbors' values. A_new was produced only from A.

---

### **Step 2 — imagine stacking another identical layer**

We feed the updated features back into the same type of layer (this is stacking).

* A_second = MLP_V(A_new) → [0.9,0.1] → [0.85, 0.15]
* B_second = MLP_V(B_new) → [0.2,0.8] → [0.12, 0.88]
* C_second = MLP_V(C_new) → [0.6,0.7] → [0.55, 0.75]

Edges and global updated similarly.

**Key mental image:** stacking layers is like running the same personal grooming routine on each person, then running it again; every person gets better at looking a bit different, but nobody has talked with anyone else.

---

### **What you should *see* in your mind**



</div>


<center><img src="GNN_bootcamp-main/images/graph_attributes.png" width="500" alt="Graph Attributes"></center>
<center><img src="GNN_bootcamp-main/images/naive_1.png" width="500" alt="Naive GNN Architecture"></center>

<small>A single layer of a simple GNN. A graph serves as the input, and each component (V, E, U) gets updated by an MLP to produce a new graph. Each function subscript indicates a separate function for a different graph attribute at the n-th layer of the GNN model.
This image illustrates a graph-independent GNN layer, where the global feature \(U_n\), node features \(V_n\), and edge features \(E_n\) are each passed through their own update functions \(f_U\), \(f_V\), and \(f_E\). These functions independently transform the features to produce \(U_{n+1}\), \(V_{n+1}\), and \(E_{n+1}\), without using the graph’s connectivity.

</small>

<i><center><small>Images from <a href="https://distill.pub/2021/gnn-intro/">Distill</a></small></center></i>


<div style="background-color:#faf9fc; padding:22px; border-radius:14px; border:1px solid #d7d7e8; color:#222; font-family:'Segoe UI', sans-serif; line-height:1.55;">

# **Cora Dataset — Overview**

The Cora dataset is a citation graph of 2,708 machine-learning research papers, divided into seven categories.  
Each paper is turned into a binary vector over 1,433 unique words, showing which words appear in that document.

The graph has 5,429 directed edges — each one means “paper A cites paper B.”

The dataset comes as two files:

* a **content** file holding each paper’s word vector and its class label,
* and a **citations** file listing all directed citation links between papers.

</div>


<center><img src="GNN_bootcamp-main/images/cora.png" width=600></center>

In [1]:
from torch_geometric.datasets import Planetoid
import torch

# Load the CORA dataset
dataset = Planetoid(root=".", name="Cora")
# Access the first graph object
data = dataset[0]
print(f"number of nodes: {data.x.shape[0]}")
print(f"number of features: {data.x.shape[1]}")
print(f"number of classes: {torch.unique(data.y).size()[0]}")

# The data object contains train_mask, val_mask, and test_mask
train_mask = data.train_mask # this is simply about the getting train data 
val_mask = data.val_mask
test_mask = data.test_mask

number of nodes: 2708
number of features: 1433
number of classes: 7


In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import torch.functional as F
from torch.utils.data import DataLoader, TensorDataset
import numpy as np

class MLP(nn.Module):
    def __init__(self, dim_in, dim_h, dim_out):
        super().__init__()
        self.linear1 = nn.Linear(dim_in, dim_h)
        self.linear2 = nn.Linear(dim_h, dim_out)

    def forward(self, x):
        x = self.linear1(x)
        x = torch.relu(x)
        x = self.linear2(x)
        return x
    
mlp = MLP(dataset.num_features, 16, dataset.num_classes)
optimizer = optim.Adam(mlp.parameters(), lr=0.01, weight_decay=5e-4)
loss_fn = nn.CrossEntropyLoss()

train_data = TensorDataset(torch.as_tensor(data.x[train_mask,:]),torch.as_tensor(data.y[train_mask]))
test_data = TensorDataset(torch.as_tensor(data.x[test_mask,:]),torch.as_tensor(data.y[test_mask]))

n_epochs = 200

def accuracy(y_pred, y_true):
    return torch.sum(y_pred == y_true) / len(y_true)


for epoch in range(n_epochs):
    prediction = mlp(train_data.tensors[0])
    loss = loss_fn(prediction,train_data.tensors[1])
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()
    train_acc = accuracy(torch.argmax(prediction, dim=1),train_data.tensors[1])

    with torch.no_grad():
        prediction = mlp(test_data.tensors[0])
        loss = loss_fn(prediction,test_data.tensors[1])
        test_acc = accuracy(torch.argmax(prediction, dim=1),test_data.tensors[1])
    if epoch%10==0:
        print(f'Epoch: {epoch}, Loss: {loss.item():.4f}, Train Accuracy: {train_acc:.4f}, Test Accuracy: {test_acc:.4f}')

Epoch: 0, Loss: 1.9194, Train Accuracy: 0.1714, Test Accuracy: 0.3320
Epoch: 10, Loss: 1.5917, Train Accuracy: 0.9929, Test Accuracy: 0.4630
Epoch: 20, Loss: 1.4418, Train Accuracy: 1.0000, Test Accuracy: 0.4900
Epoch: 30, Loss: 1.4467, Train Accuracy: 1.0000, Test Accuracy: 0.5030
Epoch: 40, Loss: 1.4761, Train Accuracy: 1.0000, Test Accuracy: 0.5010
Epoch: 50, Loss: 1.4815, Train Accuracy: 1.0000, Test Accuracy: 0.5030
Epoch: 60, Loss: 1.4600, Train Accuracy: 1.0000, Test Accuracy: 0.5120
Epoch: 70, Loss: 1.4258, Train Accuracy: 1.0000, Test Accuracy: 0.5170
Epoch: 80, Loss: 1.3980, Train Accuracy: 1.0000, Test Accuracy: 0.5190
Epoch: 90, Loss: 1.3827, Train Accuracy: 1.0000, Test Accuracy: 0.5140
Epoch: 100, Loss: 1.3717, Train Accuracy: 1.0000, Test Accuracy: 0.5200
Epoch: 110, Loss: 1.3612, Train Accuracy: 1.0000, Test Accuracy: 0.5190
Epoch: 120, Loss: 1.3547, Train Accuracy: 1.0000, Test Accuracy: 0.5190
Epoch: 130, Loss: 1.3491, Train Accuracy: 1.0000, Test Accuracy: 0.5260
Epo


It is a **2-layer MLP classifier**:

```

input → Linear → ReLU → Linear → softmax (inside CrossEntropy)

````

So yes, this is **exactly a standard NN**.

---

# **2. Your accuracy is low because an MLP *ignores the graph structure*.**

This is the **main reason**.

Cora classification depends heavily on **propagating information through the graph**.  
Papers in the same class tend to cite each other → so GNNs use edges to share features.

Your MLP sees only:

- each node's bag-of-words vector (x),
- but **not its neighbors**,  
- not its citation edges,  
- not the graph topology.

So it behaves like a **bag-of-words text classifier trained on 140 nodes** (the Cora train split).

That is **too little data**, so you get:

✔️ **Training accuracy = 100%** (overfitting)  
✔️ **Test accuracy ≈ 0.55** (no generalization)


<div style="background-color:#faf9fc; padding:22px; border-radius:14px; border:1px solid #d7d7e8; color:#222; font-family:'Segoe UI', sans-serif; line-height:1.55;">

# **DeepWalk — simple, intuitive explanation**

*DeepWalk* is a method that learns vector representations for nodes in a graph using ideas borrowed from language modeling.  
It basically treats walks on a graph the same way word sequences are treated in text, and uses that to learn useful embeddings.

---

## **How DeepWalk works (two main steps)**

### **1. Random Walks**

DeepWalk starts by exploring the graph through random walks:

- For each node, it generates a fixed number \(k\) of random paths.
- Each path has a fixed length \(l\).
- These sequences of nodes act like “sentences.”

The idea is simple:  
nodes that show up near each other in many of these walks should have similar embeddings, because they live in similar neighborhoods in the graph.

---

### **2. SkipGram**

After generating random walks, DeepWalk uses the **SkipGram** model (from the original word2vec paper by Mikolov et al.) to learn embeddings.

SkipGram does this by:

- Taking a sequence (like a sentence),
- Looking at windows of nearby items,
- And making items that appear in the same context end up with similar embeddings.

In text, this means similar words have similar vectors.  
In DeepWalk, it means nodes that appear close together in random walks become similar in vector space.

A good intuitive introduction to SkipGram is here:  
https://mccormickml.com/2016/04/19/word2vec-tutorial-the-skip-gram-model/

---

## **How SkipGram is applied to graphs**

DeepWalk treats each random walk like a sentence:

- Each walk is a sequence of nodes.
- The “context window” works the same way: nodes that appear close together in the walk are considered related.
- Embeddings start as random vectors.
- Using gradient descent, the model adjusts them so that nodes appearing together get closer in the embedding space.

Essentially, the neural network learns to place similar nodes near each other.

---

<center><img src="GNN_bootcamp-main/images/deepwalk.jpg" width=400></center>
<center><small>image from https://www.geeksforgeeks.org/deepwalk-algorithm/</small></center>

</div>


Example of DeepWalk in Python:

To use DeepWalk for node classification on the Cora dataset, we'll follow these steps:

- Load the Cora dataset.
- Generate random walks to capture the local structure of the graph.
- Learn node embeddings using the SkipGram model.
- Train a classifier (e.g., logistic regression) using the learned embeddings.

In [3]:
import random

def generate_random_walks(G, num_walks, walk_length):
    walks = []
    nodes = list(G.nodes())
    for _ in range(num_walks):
        random.shuffle(nodes)
        for node in nodes:
            walk = [node]
            while len(walk) < walk_length:
                cur = walk[-1]
                neighbors = list(G.neighbors(cur))
                if neighbors:
                    walk.append(random.choice(neighbors))
                else:
                    break
            walks.append(walk)
    return walks

In [4]:
from nodevectors import Node2Vec
from torch_geometric.datasets import Planetoid
import torch_geometric
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
# Load Cora dataset
dataset = Planetoid(root=".", name="Cora")
data = dataset[0]

# The data object contains train_mask, val_mask, and test_mask
train_mask = data.train_mask
val_mask = data.val_mask
test_mask = data.test_mask

# Convert to NetworkX graph for random walk generation

# The starting vertex is each node in the graph, one-by-one, after a random shuffle.

G = torch_geometric.utils.to_networkx(data, to_undirected=True)
# Parameters
num_walks = 10
walk_length = 80
# Generate random walks
walks = generate_random_walks(G, num_walks, walk_length)


In [ ]:
from gensim.models import Word2Vec

# Convert walks to strings for gensim
walks_str = [[str(node) for node in walk] for walk in walks]

# Train Word2Vec model
model = Word2Vec(walks_str, vector_size=128, window=10, min_count=0, sg=1, workers=4, epochs=10)

# Extract embeddings
node_embeddings = {int(node): model.wv[str(node)] for node in G.nodes()}

# Prepare data for classification
X_train = np.array([node_embeddings[node.item()] for node in torch.where(train_mask)[0]])
y_train = np.array(data.y[train_mask])

# Train logistic regression classifier
classifier = LogisticRegression(max_iter=1000)
classifier.fit(X_train, y_train)

# Evaluate the classifier
X_test = np.array([node_embeddings[node.item()] for node in torch.where(test_mask)[0]])
y_test = np.array(data.y[test_mask])
y_pred = classifier.predict(X_test)
accuracy = accuracy_score(y_test, y_pred)
print(f'Test Accuracy of DeepWalk is: {accuracy:.4f}')

Test Accuracy of DeepWalk is: 0.7020


<div style="background:#f7f7f7; padding:18px; border-radius:10px;">

## Vanilla Neural Network

A vanilla neural network processes each node **independently**, using only its feature vector.  
It has **no access to edges or connections**, so it cannot use graph structure.

---

## Graph Structure

Graphs have nodes and edges, and the **pattern of connections itself carries information**  
(e.g., proximity, communities, structural roles).  
A vanilla NN cannot see any of this.

---

## DeepWalk

DeepWalk uses **only graph connectivity**.  
It performs random walks (A → B → C → …) and learns embeddings like word2vec.  
Nodes that frequently appear together in walks get similar vectors.  
It **ignores node features** entirely.

---

## Vanilla NN vs. DeepWalk

- **Vanilla NN:** uses features, ignores edges  
- **DeepWalk:** uses edges, ignores features  

They capture opposite halves of the graph’s information.

---

## Why Combine Both?

Real tasks require **attributes + structure**.  
Example: paper classification needs both the paper’s text (features) and its citation links (structure).

---

## Integrated Methods: GNNs

Graph Neural Networks combine both worlds:  
each node **aggregates features from its neighbors** and mixes them with its own.  
The result represents both **what the node is** and **who it is connected to**.

---

## One-Sentence Summary

Vanilla NNs see only features, DeepWalk sees only structure, and GNNs combine both for complete graph understanding.

</div>

<center><img src="GNN_bootcamp-main/images/Two-extremes.png" width=500></center>



<!-- Option A: HTML box + LaTeX (works in Jupyter/MathJax-enabled viewers) -->
<div style="background:#f7f7f7; padding:18px; border-radius:10px; line-height:1.45;">

## What we start with
- A graph: nodes connected by edges (e.g., A—B, A—C).  
- Feature matrix $X \in \mathbb{R}^{n\times d}$.  
  Example ($n=3, d=2$):

$$X = \begin{bmatrix} 1.0 & 0.5\\[4pt] 0.2 & 0.1\\[4pt] 0.7 & 0.8 \end{bmatrix}$$

---
<center><img src="GNN_bootcamp-main/images/gcn_intro.png" width="300"></center>

## Vanilla neural layer (baseline)
- Formula:
$$H^{(1)} = \sigma(XW)$$
- Meaning: apply a regular NN layer to each node independently (edges ignored).

**Example:** Node A update = $\sigma([1.0,\,0.5]W)$ — no influence from B,C.

---

## Bring in graph structure (adjacency)
- Let A be the adjacency matrix, where $A_{ij}=1$ if $i$ connects to $j$.
- New idea:
$$H^{(1)} = \sigma(A X W)$$
- Effect: each row becomes the sum of neighbors' features (node does not include its own feature yet).

**Example:** If A connects to B,C, then row for A in AX = $x_B + x_C$.


<center><img src="GNN_bootcamp-main/images/GCN_naive.png" width="500"></center>


---

## Add self-loops (include node itself)
- Define:
$$\tilde{A} = A + I$$
- Now $\tilde{A}X$ aggregates self + neighbors.

**Example:** row(A) = $x_A + x_B + x_C$.

---

## Degree imbalance problem
- Nodes with many neighbors sum many vectors → large magnitude; nodes with few neighbors get small magnitude — this biases training.

---

## Normalize with degree
- Degree matrix:
$$\tilde{D}_{ii} = \sum_j \tilde{A}_{ij}$$
- Symmetric normalization:
$$\tilde{A}_{\text{norm}} = \tilde{D}^{-1/2}\,\tilde{A}\,\tilde{D}^{-1/2}$$
This keeps the operator symmetric and stabilizes training.

---

## Final GCN propagation rule
$$H^{(1)} = \sigma\!\left(\tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2} X W\right)$$

---

## Mini numerical example (corrected)
Node feature vectors:
$$x_A=[1,1],\quad x_B=[2,0],\quad x_C=[0,3]$$

Adjacency (no self-loops initially):
$$A=\begin{bmatrix}0&1&1\\[4pt]1&0&0\\[4pt]1&0&0\end{bmatrix} \quad\Rightarrow\quad \tilde{A}=A+I=\begin{bmatrix}1&1&1\\[4pt]1&1&0\\[4pt]1&0&1\end{bmatrix}$$

Degrees:
$$\tilde{D}=\mathrm{diag}(3,\;2,\;2)$$

Aggregate (row sums):
$$\tilde{A}X= \begin{bmatrix} x_A+x_B+x_C\\[4pt] x_B+x_A\\[4pt] x_C+x_A \end{bmatrix} = \begin{bmatrix} 3 & 4\\[4pt] 3 & 1\\[4pt] 1 & 4 \end{bmatrix}$$

Apply symmetric normalization exactly:
$$\tilde{D}^{-1/2}= \mathrm{diag}\!\left(\tfrac{1}{\sqrt{3}},\tfrac{1}{\sqrt{2}},\tfrac{1}{\sqrt{2}}\right)$$
So
$$\tilde{A}_{\text{norm}}=\tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2} = \begin{bmatrix} \tfrac{1}{3} & \tfrac{1}{\sqrt{6}} & \tfrac{1}{\sqrt{6}}\\[6pt] \tfrac{1}{\sqrt{6}} & \tfrac{1}{2} & 0\\[6pt] \tfrac{1}{\sqrt{6}} & 0 & \tfrac{1}{2} \end{bmatrix}$$

Normalized node features $=\tilde{A}_{\text{norm}} X$. Numerically:
$$\tilde{A}_{\text{norm}}X \approx \begin{bmatrix} (1/3)\cdot[1,1] + (1/\sqrt6)\cdot[2,0] + (1/\sqrt6)\cdot[0,3]\\[4pt] (1/\sqrt6)\cdot[1,1] + (1/2)\cdot[2,0]\\[4pt] (1/\sqrt6)\cdot[1,1] + (1/2)\cdot[0,3] \end{bmatrix} \approx \begin{bmatrix} [1.149,\;1.558]\\[4pt] [1.408,\;0.408]\\[4pt] [0.408,\;1.908] \end{bmatrix}$$

Then apply $W$ and $\sigma$ to get the final layer output.

---

## Ultra-compact checklist
- $XW$: vanilla NN, ignores neighbors.  
- $A X W$: neighbors only, ignores self.  
- $(A+I) X W$: includes self, unnormalized (high-degree inflation).  
- $\tilde{D}^{-1/2}(A+I)\tilde{D}^{-1/2}$: symmetric normalization (GCN).  
- Final: $H=\sigma(\tilde{D}^{-1/2}(A+I)\tilde{D}^{-1/2} X W)$.

</div>


<!-- GCN: Formal explanation (KaTeX-safe) -->
<div style="background:#f7f7f7; padding:18px; border-radius:10px; line-height:1.45;">

## Clear, step-by-step explanation: “GCN — more formal”

I’ll structure it as:
1. What the objects mean  
2. What message passing means  
3. What the GCN formula is doing  
4. How convolution appears in graphs  
5. Intuition tie-back to your A–B–C–D graph

---

## 1. What the objects mean

- $H^{(0)} = X$ — initial node features (e.g., vectors for A, B, C, D).  
- $H^{(l-1)}$ — feature matrix from the previous layer.  
- $W$ — learned weight matrix (like in standard neural nets).  
- $A$ — adjacency matrix (which nodes are connected).  
- $A+I$ — adjacency with self-loops (each node includes itself).  
- $D$ — degree matrix (diagonal; counts neighbors).  
- $D^{-1/2}(A+I)D^{-1/2}$ — symmetric normalized adjacency (balances nodes with different degrees).

---

## 2. Message Passing: the core idea

Message passing steps:
- Each node sends its current feature vector to neighbors.
- Each node receives neighbors' vectors.
- Each node aggregates received vectors (sum or average).
- Apply a learned linear transform $W$.
- Apply a nonlinearity $\sigma$ (e.g., ReLU).

<center><img src="GNN_bootcamp-main/images/GCN_overview.png" width="500"></center>

Intuition: a node updates by “looking around itself.”  
Example for node A:
- neighbors: B, C  
- receives x_B and x_C, aggregates them (plus optionally x_A if self-looped), then applies $W$ and $\sigma$.

<center><img src="GNN_bootcamp-main/images/message_passing.gif"></center>

---

## 3. The GCN formula explained slowly

A single GCN layer:
$$H^{(l)} = \sigma\!\big( \tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2}\,H^{(l-1)}\,W \big), \qquad \tilde{A}=A+I$$

Step-by-step:
1. Add self-loops: $\tilde{A}=A+I$. Each node includes its own features in the aggregate.
2. Compute degrees: $\tilde{D}_{ii}=\sum_j \tilde{A}_{ij}$.
3. Symmetric normalization: $\tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2}$ — prevents high-degree nodes from dominating.
4. Aggregate: $\tilde{A}_{\text{norm}}\,H^{(l-1)}$ — each row becomes the normalized blend of a node’s neighborhood features.
5. Linear transform: $(\cdots)W$ — mixes feature dimensions (same as a dense layer).
6. Nonlinearity: $\sigma(\cdot)$ — introduces nonlinearity and enables deeper stacking.

Notes:
- Normalization makes contributions proportional rather than additive with degree.
- Using the symmetric form keeps the operator self-adjoint (useful for stability).


---

## 4. Where is the “convolution”?

Analogy with CNNs:
- CNN: a filter slides over a grid, collects a pixel and nearby pixels, applies a shared kernel.
- GCN: a filter sits on each node, collects that node and its neighbors, applies a shared linear operator $W$.

Convolution roles:
- Neighborhood extractor: $\tilde{D}^{-1/2}\tilde{A}\tilde{D}^{-1/2}$.
- Shared filter: $W$.
Thus GCN implements a graph-aware, parameter-shared local aggregation — the graph version of convolution.

---

## 5. Tie-back to the A–B–C–D graph

Using your graph:
- A receives messages from A, B, C (if self-loops included).  
- B receives A, B, C, D.  
- C receives A, B, C.  
- D receives B, D.

After normalization:
- Each neighbor group is averaged/weighted so no single node’s degree overpowers others.
- Applying $W$ changes feature dimensionality and abstracts features.
- Stack layers to increase receptive field:
  - 1 layer → 1-hop neighbors,
  - 2 layers → 2-hop neighbors,
  - etc.

GCNs are powerful because repeated local aggregations plus learned transforms let nodes encode progressively larger graph context.

---

## Okay... but where is the convolution?

In fact, a Graph Convolutional Neural Network (GCN) performs operations similar to those in Convolutional Neural Networks (CNNs) used for images. In a GCN, we can think of the message passing process as moving a filter (or kernel) over each node in the graph. When the filter is on a node, it gathers and combines data from nearby nodes to create the output for that node."

<img src="GNN_bootcamp-main/images/CNN_filter.png" style="width: 45%; display: inline-block;">
<img src="GNN_bootcamp-main/images/GCN_filter.png" style="width: 45%; display: inline-block;">
<center>convolution in CNN vs convolution in GCN</center>
Very similar to CNN, for GCNs, a filter is passed over each node and the values of the **neighboring nodes** are combined to form the output value at the next layer.


</div>


In [14]:
# Manual GCN implementation for Cora that follows:
# H^{(l)} = sigma( D^{-1/2} (A+I) D^{-1/2} H^{(l-1)} W )
# - Computes A, A+I, D, D^{-1/2} (A+I) D^{-1/2}
# - Uses these matrices directly (manual propagation) so it's explicit and educational
# - Trains a 2-layer GCN end-to-end and evaluates logistic regression on hidden embeddings
# Note: requires torch and torch_geometric

import os
import random
import numpy as np
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

# torch_geometric utilities
try:
    from torch_geometric.datasets import Planetoid
    from torch_geometric.utils import to_dense_adj, add_self_loops
except Exception as e:
    raise ImportError("Please install torch_geometric. See https://pytorch-geometric.readthedocs.io/") from e

# Reproducibility
seed = 42
random.seed(seed)
np.random.seed(seed)
torch.manual_seed(seed)

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# ---------------------------
# Load Cora
# ---------------------------
dataset = Planetoid(root="data/Planetoid", name="Cora")
data = dataset[0].to(device)
N = data.num_nodes
F_in = data.num_node_features
num_classes = dataset.num_classes
print(f"Cora: N={N}, features={F_in}, classes={num_classes}")

# ---------------------------
# Build dense adjacency A (N x N)
# ---------------------------
# to_dense_adj returns shape [batch, N, N], batch=1 for single graph
A_dense = to_dense_adj(data.edge_index, max_num_nodes=N)[0].to(device)  # tensor float (0/1)
A_dense = A_dense.to(dtype=torch.float32)

# Print a small part
print("A (sample rows):")
print(A_dense[:6, :6].cpu().numpy())

# ---------------------------
# Add self-loops: A_hat = A + I
# ---------------------------
I = torch.eye(N, device=device)
A_hat = A_dense + I

print("\nA + I (sample rows):")
print(A_hat[:6, :6].cpu().numpy())

# ---------------------------
# Degree matrix D_hat and D_hat^{-1/2}
# ---------------------------
deg = A_hat.sum(dim=1)            # shape [N]
# Avoid division by zero (shouldn't happen after self-loops)
deg_inv_sqrt = torch.pow(deg, -0.5)
deg_inv_sqrt[torch.isinf(deg_inv_sqrt)] = 0.0
D_inv_sqrt = torch.diag(deg_inv_sqrt)

print("\nDegrees (first 10):", deg[:10].cpu().numpy())

# ---------------------------
# Symmetric normalized adjacency: A_norm = D^{-1/2} * A_hat * D^{-1/2}
# ---------------------------
A_norm = D_inv_sqrt @ A_hat @ D_inv_sqrt
print("\nA_norm (sample rows):")
print(A_norm[:6, :6].cpu().numpy())

# ---------------------------
# Quick check: A_norm should be symmetric (numerically)
# ---------------------------
sym_diff = (A_norm - A_norm.t()).abs().max().item()
print("\nSymmetry check max |A_norm - A_norm^T| =", sym_diff)

# ---------------------------
# Manual GCN model (explicit matrix multiplications)
# ---------------------------
class ManualGCN(nn.Module):
    def __init__(self, in_feats, hidden_feats, out_feats, A_norm):
        super().__init__()
        # store normalized adjacency as buffer (not a parameter)
        self.register_buffer("A_norm", A_norm)  # shape [N, N]
        self.W1 = nn.Parameter(torch.randn(in_feats, hidden_feats) * 0.1)
        self.W2 = nn.Parameter(torch.randn(hidden_feats, out_feats) * 0.1)
        self.dropout = 0.5

    def forward(self, X):
        # X: [N, F_in]
        # 1st layer: H1 = sigma( A_norm @ X @ W1 )
        H1 = self.A_norm @ X @ self.W1
        H1 = F.relu(H1)
        H1 = F.dropout(H1, p=self.dropout, training=self.training)
        # 2nd layer: logits = A_norm @ H1 @ W2
        logits = self.A_norm @ H1 @ self.W2
        return logits, H1  # return logits and hidden embeddings

# instantiate model
hidden_dim = 16
model = ManualGCN(in_feats=F_in, hidden_feats=hidden_dim, out_feats=num_classes, A_norm=A_norm).to(device)

optimizer = optim.Adam([p for p in model.parameters()], lr=0.01, weight_decay=5e-4)

# ---------------------------
# Training loop
# ---------------------------
def train_epoch():
    model.train()
    optimizer.zero_grad()
    logits, _ = model(data.x)
    loss = F.cross_entropy(logits[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    return loss.item()

@torch.no_grad()
def evaluate():
    model.eval()
    logits, H1 = model(data.x)
    preds = logits.argmax(dim=1)
    accs = []
    for mask in [data.train_mask, data.val_mask, data.test_mask]:
        correct = preds[mask].eq(data.y[mask]).sum().item()
        acc = correct / int(mask.sum().item())
        accs.append(acc)
    return tuple(accs), logits.cpu().numpy(), H1.cpu().numpy()

best_val = 0.0
best_test_at_best_val = 0.0
best_epoch = 0
num_epochs = 200

for epoch in range(1, num_epochs + 1):
    loss = train_epoch()
    (train_acc, val_acc, test_acc), logits_np, H1_np = evaluate()
    if val_acc > best_val:
        best_val = val_acc
        best_test_at_best_val = test_acc
        best_epoch = epoch
    if epoch == 1 or epoch % 20 == 0:
        print(f"Epoch {epoch:03d} | Loss {loss:.4f} | Train {train_acc:.4f} | Val {val_acc:.4f} | Test {test_acc:.4f}")

print(f"Best val {best_val:.4f} @ epoch {best_epoch}, Test at that val = {best_test_at_best_val:.4f}")

# ---------------------------
# Inspect A_norm @ X (structure-aware features BEFORE applying W)
# ---------------------------
with torch.no_grad():
    A_norm_X = A_norm @ data.x
print("\n(A_norm @ X) sample rows (first 6):")
print(A_norm_X[:6].cpu().numpy())

# ---------------------------
# Use hidden embeddings H1 for logistic regression
# ---------------------------
train_idx = np.where(data.train_mask.cpu().numpy())[0]
test_idx = np.where(data.test_mask.cpu().numpy())[0]
y = data.y.cpu().numpy()

X_train = H1_np[train_idx]
y_train = y[train_idx]
X_test = H1_np[test_idx]
y_test = y[test_idx]

clf = LogisticRegression(max_iter=1000, multi_class="ovr")
clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
acc_lr = accuracy_score(y_test, y_pred)
print(f"\nLogistic regression on hidden GCN embeddings (test) accuracy: {acc_lr:.4f}")



Device: cpu
Cora: N=2708, features=1433, classes=7
A (sample rows):
[[0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0.]]

A + I (sample rows):
[[1. 0. 0. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 1. 1. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 1.]]

Degrees (first 10): [4. 4. 6. 2. 6. 4. 5. 2. 4. 3.]

A_norm (sample rows):
[[0.25       0.         0.         0.         0.         0.        ]
 [0.         0.25       0.20412414 0.         0.         0.        ]
 [0.         0.20412414 0.16666666 0.         0.         0.        ]
 [0.         0.         0.         0.49999997 0.         0.        ]
 [0.         0.         0.         0.         0.16666666 0.        ]
 [0.         0.         0.         0.         0.         0.25      ]]

Symmetry check max |A_norm - A_norm^T| = 0.0
Epoch 001 | Loss 1.9471 | Train 0.2857 | Val 0.1120 | Test 0.1350
Epoch 020 | Loss 0.6076 | Train 0.9857 | Val 0.7500 |

C:\Users\User\AppData\Roaming\Python\Python310\site-packages\sklearn\linear_model\_logistic.py:1256: FutureWarning: 'multi_class' was deprecated in version 1.5 and will be removed in 1.7. Use OneVsRestClassifier(LogisticRegression(..)) instead. Leave it to its default value to avoid this warning.
  warnings.warn(
